import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>

          <h1>Lyrico</h1>
        </div>

        <div className={styles.center}>
          <h1>Lyri</h1>
          <div className={styles.thirteen}>
            <h1> Co </h1>
          </div>
        </div>

        <div className={styles.grid}>
          <Link
            href="/all"
            className={styles.card}
          >
            <h2 className={inter.className}>
              all lyrics and chords <span>-&gt;</span>
            </h2>
            {/* <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p> */}
          </Link>

          <Link
            href="/artists"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Artists <span>-&gt;</span>
            </h2>

          </Link>

          <Link
            href="/chords"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Chords <span>-&gt;</span>
            </h2>

          </Link>

          <Link
            href="/setting"
            className={styles.card}
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>

          </Link>
        </div>
      </main>
    </>
  )
}
